### ISSUE TITLE
Check for missing data

### ISSUE THREAD

**Issue by rukku** [maning/open-hazards-ph#13]
![image](https://user-images.githubusercontent.com/284046/75207959-2c2c0180-57b5-11ea-903c-b149489b3d45.png)
 
@maning has reported that data appears to be incomplete.

**Comment by maning** [comment]
It looks like rendering issue in QGIS.  I created a vrt of all existing files, see below:

**DTM** (1,404 files)
<img width="873" alt="Screenshot 2020-03-03 21 38 42" src="https://user-images.githubusercontent.com/353700/75782526-fd57f180-5d99-11ea-8a25-547313f3010f.png">

**DSM** (1,396 files)
<img width="866" alt="Screenshot 2020-03-03 22 17 37" src="https://user-images.githubusercontent.com/353700/75784246-e49d0b00-5d9c-11ea-8201-1bc314351d38.png">

**Ortho** (543 files)
<img width="869" alt="Screenshot 2020-03-03 21 43 12" src="https://user-images.githubusercontent.com/353700/75782596-18c2fc80-5d9a-11ea-8383-490f5356ff07.png">

Closing as not an issue, apologies for the noise @rukku
