### ISSUE TITLE
MGB hazard maps at geoportalPH

### ISSUE THREAD

**Issue by ricsatjr** [maning/open-hazards-ph#15]
Hi Maning, 

How about the MGB hazard maps at geoportal.gov.ph? Can we download and put these here?

Cheers,

Ric

**Comment by maning** [comment]
@ricsatjr Is there a download end point I can do bulk download and what is the license by geoportal.gov.ph?

**Comment by ricsatjr** [comment]
Sorry, just got back to this. There is no explicit license provided in geoportal.gov.ph.
